Fail the molecule eos_cli_config_gen

diff --git a/.github/workflows/pull-request-management.yml b/.github/workflows/pull-request-management.yml
--- a/.github/workflows/pull-request-management.yml
+++ b/.github/workflows/pull-request-management.yml
@@ -225,7 +225,13 @@ jobs:
         run: "/venvs/UV3.11/bin/python -m pip install '${{ matrix.ansible_version }}' --upgrade"
       - name: Run molecule action
         run: " . /venvs/UV3.11/bin/activate && cd ansible_collections/arista/avd && molecule test --scenario-name ${{ matrix.avd_scenario }}"
-      # - uses: actions/upload-artifact@v4
+      - name: Check status
+        run: |
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "❌ Changes detected! Failing the job..."
+            git diff
+            exit 1
+        # - uses: actions/upload-artifact@v4
       #   with:
       #     name: molecule-${{ matrix.avd_scenario }}-artifacts
       #     path: ${PWD}/ansible_collections/arista/avd/molecule/${{ matrix.avd_scenario }}
