container_process25

diff --git a/.github/workflows/pull-request-management.yml b/.github/workflows/pull-request-management.yml
--- a/.github/workflows/pull-request-management.yml
+++ b/.github/workflows/pull-request-management.yml
@@ -135,55 +135,99 @@ jobs:
 
           # Install python versions
           RUN uv python install 3.10 3.11 3.12 3.13
+          # Create the parallel_install.sh script dynamically
+          RUN echo '#!/bin/bash\n\
+          set -e\n\
+          \n\
+          # Function to create virtual environment, clone repo, and install dependencies\n\
+          create_venv_and_install() {\n\
+            local version=$1\n\
+            local dir=$2\n\
+            echo "Starting UV venv for Python $version in $dir..."\n\
+          \n\
+            uv venv --python $version $dir\n\
+            $dir/bin/python -m ensurepip --upgrade\n\
+            source $dir/bin/activate\n\
+            git clone https://github.com/${GITHUB_REPOSITORY} repo_$dir\n\
+            cd repo_$dir\n\
+            $dir/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml "ansible-core<2.19.0" \\\n\
+              -r .github/requirements-ci.txt \\\n\
+              -r ansible_collections/arista/avd/requirements-dev.txt --upgrade\n\
+          \n\
+            echo "Completed installation in $dir"\n\
+          }\n\
+          \n\
+          # Start parallel tasks\n\
+          create_venv_and_install 3.10 UV3.10 &\n\
+          create_venv_and_install 3.11 UV3.11 &\n\
+          create_venv_and_install 3.12 UV3.12 &\n\
+          create_venv_and_install 3.13 UV3.13 &\n\
+          \n\
+          # Wait for all processes to finish\n\
+          wait\n\
+          status=$?\n\
+          \n\
+          # Check the final status\n\
+          if [ $status -ne 0 ]; then\n\
+            echo "One or more processes failed."\n\
+            exit 1\n\
+          fi\n\
+          \n\
+          echo "All processes completed successfully."' > /usr/local/bin/parallel_install.sh
 
-          # Clone the repository in each virtual environment into unique directories
-          RUN set -e; \
-            bash -c " \
-                ( uv venv --python 3.10 UV3.10 && \
-                  UV3.10/bin/python -m ensurepip --upgrade && \
-                  source UV3.10/bin/activate && \
-                  git clone https://github.com/${{ github.repository }} repo_UV3.10 && \
-                  cd repo_UV3.10 && \
-                  ../UV3.10/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml \"ansible-core<2.19.0\" \
-                  -r .github/requirements-ci.txt -r ansible_collections/arista/avd/requirements-dev.txt --upgrade ) & \
-                pid1=\$! && \
-                ( uv venv --python 3.11 UV3.11 && \
-                  UV3.11/bin/python -m ensurepip --upgrade && \
-                  source UV3.11/bin/activate && \
-                  git clone https://github.com/${{ github.repository }} repo_UV3.11 && \
-                  cd repo_UV3.11 && \
-                  ../UV3.11/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml \"ansible-core<2.19.0\" \
-                  -r .github/requirements-ci.txt -r ansible_collections/arista/avd/requirements-dev.txt --upgrade ) & \
-                pid2=\$! && \
-                ( uv venv --python 3.12 UV3.12 && \
-                  UV3.12/bin/python -m ensurepip --upgrade && \
-                  source UV3.12/bin/activate && \
-                  git clone https://github.com/${{ github.repository }} repo_UV3.12 && \
-                  cd repo_UV3.12 && \
-                  ../UV3.12/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml \"ansible-core<2.19.0\" \
-                  -r .github/requirements-ci.txt -r ansible_collections/arista/avd/requirements-dev.txt --upgrade ) & \
-                pid3=\$! && \
-                ( uv venv --python 3.13 UV3.13 && \
-                  UV3.13/bin/python -m ensurepip --upgrade && \
-                  source UV3.13/bin/activate && \
-                  git clone https://github.com/${{ github.repository }} repo_UV3.13 && \
-                  cd repo_UV3.13 && \
-                  UV3.13/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml \"ansible-core<2.19.0\" \
-                  -r .github/requirements-ci.txt -r ansible_collections/arista/avd/requirements-dev.txt --upgrade ) & \
-                pid4=\$! && \
-                wait \$pid1; status1=\$?; \
-                wait \$pid2; status2=\$?; \
-                wait \$pid3; status3=\$?; \
-                wait \$pid4; status4=\$?; \
-                echo \"Status of pid1: \$status1\"; \
-                echo \"Status of pid2: \$status2\"; \
-                echo \"Status of pid3: \$status3\"; \
-                echo \"Status of pid4: \$status4\"; \
-                if [ \$status1 -ne 0 ] || [ \$status2 -ne 0 ] || [ \$status3 -ne 0 ] || [ \$status4 -ne 0 ]; then \
-                  echo \"One or more processes failed.\"; \
-                  exit 1; \
-                fi; \
-                echo \"All processes completed successfully.\""
+          # Make the script executable
+          RUN chmod +x /usr/local/bin/parallel_install.sh
+
+          # Run the script
+          RUN /usr/local/bin/parallel_install.sh
+          # # Clone the repository in each virtual environment into unique directories
+          # RUN set -e; \
+          #   bash -c " \
+          #       ( uv venv --python 3.10 UV3.10 && \
+          #         UV3.10/bin/python -m ensurepip --upgrade && \
+          #         source UV3.10/bin/activate && \
+          #         git clone https://github.com/${{ github.repository }} repo_UV3.10 && \
+          #         cd repo_UV3.10 && \
+          #         ../UV3.10/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml \"ansible-core<2.19.0\" \
+          #         -r .github/requirements-ci.txt -r ansible_collections/arista/avd/requirements-dev.txt --upgrade ) & \
+          #       pid1=\$! && \
+          #       ( uv venv --python 3.11 UV3.11 && \
+          #         UV3.11/bin/python -m ensurepip --upgrade && \
+          #         source UV3.11/bin/activate && \
+          #         git clone https://github.com/${{ github.repository }} repo_UV3.11 && \
+          #         cd repo_UV3.11 && \
+          #         ../UV3.11/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml \"ansible-core<2.19.0\" \
+          #         -r .github/requirements-ci.txt -r ansible_collections/arista/avd/requirements-dev.txt --upgrade ) & \
+          #       pid2=\$! && \
+          #       ( uv venv --python 3.12 UV3.12 && \
+          #         UV3.12/bin/python -m ensurepip --upgrade && \
+          #         source UV3.12/bin/activate && \
+          #         git clone https://github.com/${{ github.repository }} repo_UV3.12 && \
+          #         cd repo_UV3.12 && \
+          #         ../UV3.12/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml \"ansible-core<2.19.0\" \
+          #         -r .github/requirements-ci.txt -r ansible_collections/arista/avd/requirements-dev.txt --upgrade ) & \
+          #       pid3=\$! && \
+          #       ( uv venv --python 3.13 UV3.13 && \
+          #         UV3.13/bin/python -m ensurepip --upgrade && \
+          #         source UV3.13/bin/activate && \
+          #         git clone https://github.com/${{ github.repository }} repo_UV3.13 && \
+          #         cd repo_UV3.13 && \
+          #         UV3.13/bin/python -m pip install mock pytest pytest-mock pytest-xdist pyyaml \"ansible-core<2.19.0\" \
+          #         -r .github/requirements-ci.txt -r ansible_collections/arista/avd/requirements-dev.txt --upgrade ) & \
+          #       pid4=\$! && \
+          #       wait \$pid1; status1=\$?; \
+          #       wait \$pid2; status2=\$?; \
+          #       wait \$pid3; status3=\$?; \
+          #       wait \$pid4; status4=\$?; \
+          #       echo \"Status of pid1: \$status1\"; \
+          #       echo \"Status of pid2: \$status2\"; \
+          #       echo \"Status of pid3: \$status3\"; \
+          #       echo \"Status of pid4: \$status4\"; \
+          #       if [ \$status1 -ne 0 ] || [ \$status2 -ne 0 ] || [ \$status3 -ne 0 ] || [ \$status4 -ne 0 ]; then \
+          #         echo \"One or more processes failed.\"; \
+          #         exit 1; \
+          #       fi; \
+          #       echo \"All processes completed successfully.\""
 
           # # Clone the repository in each virtual environment and install requirements in parallel
           # RUN ( \
